Fix org.opentest4j.AssertionFailedError
```
org.opentest4j.AssertionFailedError: <?jelly escape-by-default='true'?> is missing in file:/Users/sue445/workspace/github.com/jenkinsci/yaml-axis-plugin/target/classes/index.jelly
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:42)
	at org.junit.jupiter.api.Assertions.fail(Assertions.java:143)

```